# This is a basic workflow to help you get started with Actions

name: Report

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: 
      - master
  schedule:
    - cron: '0 0,4,8,12,16,20 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  report:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        # in this example, there is a newer version already installed, 3.7.7, so the older version will be downloaded
        python-version: ['3.9']

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script

     
      run: |
        python -m pip install --upgrade pip
        python -m pip install time 
        python -m pip install requests 
        python -m pip install random 
        python -m pip install fake_useragent
        python -m pip install eventlet
        python autorefresh.py  
